services:
  - type: web
    name: StreakFit
    env: node
    region: oregon
    plan: free
    buildCommand: npm run build && cd server && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
    healthCheckPath: /api/health
